/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Addbutton: typeof import('./../components/Button/addbutton/index.vue')['default']
    Addvue: typeof import('./../components/addvue/index.vue')['default']
    Aside: typeof import('./../components/Aside/index.vue')['default']
    BarBackround: typeof import('./../components/barBackround/index.vue')['default']
    Card: typeof import('./../components/card/index.vue')['default']
    Chart2: typeof import('./../components/chart2/index.vue')['default']
    Chart3: typeof import('./../components/chart3/index.vue')['default']
    Charts: typeof import('./../components/charts/index.vue')['default']
    Checkbox: typeof import('./../components/Button/checkbox/index.vue')['default']
    Header: typeof import('./../components/Header/index.vue')['default']
    IconSelect: typeof import('./../components/IconSelect/index.vue')['default']
    Linechar: typeof import('./../components/linechar/index.vue')['default']
    LineChar: typeof import('./../components/lineChar/index.vue')['default']
    Main: typeof import('./../components/Main/index.vue')['default']
    PicShow: typeof import('./../components/PicShow/index.vue')['default']
    Piechar: typeof import('./../components/Piechar/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sixchar: typeof import('./../components/sixchar/index.vue')['default']
    SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
  }
}
